ContentManagementSystem/ContentManagementSystem/ContentManagementSystem.UI/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using ContentManagementSystem.BLL.Contracts;
using ContentManagementSystem.BLL.Managers;
using ContentManagementSystem.BLL.NinjectBindings;
using ContentManagementSystem.UI.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Ninject;

namespace ContentManagementSystem.UI.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        private readonly IStaticPageManager _staticPageManager;

        public RoleController()
        {
            var kernel = new StandardKernel(new BllBindings());
            kernel.Load(Assembly.GetExecutingAssembly());
            _staticPageManager = kernel.Get<IStaticPageManager>();
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            var r = _staticPageManager.GetAll();

            if (!r.Success)
            {
                SetErrorViewData(r.Message);
            }

            ViewData["StaticPages"] = r.Data.Where(sp => sp.IsLive).ToList();
        }

        private void SetErrorViewData(string message)
        {
            ViewData["Alert"] = "alert-danger";
            ViewData["Message"] = message;
        }

        // GET: All Roles
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }

        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }

        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(IdentityRole Role)
        {
            var myRole = context.Roles.FirstOrDefault(m => m.Id == Role.Id);
            context.Roles.Remove(myRole);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult AssignAccountRole()
        {
            var UsersAndRoles = new RolesAndUsersViewModel();
            if (User.IsInRole("Admin"))
            {
                UsersAndRoles.AllUsers = context.Users.ToList();
                UsersAndRoles.AllRoles = context.Roles.Where(r => r.Name != "Admin").ToList();
                foreach (var user in UsersAndRoles.AllUsers)
                {
                    if(user.Roles.Count == 0)
                     {
                        user.Roles.Add(new IdentityUserRole { RoleId = "0", UserId = user.Id });
                    }
                }
                context.SaveChanges();
                return View(UsersAndRoles);
            }
            else
            {
                return View("Index");
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult SaveUserRole(string userId, string roleId)
        {
            var user = context.Users.Single(u => u.Id == userId);
            user.Roles.Clear();
            user.Roles.Add(new IdentityUserRole {RoleId = roleId, UserId = userId});

            context.SaveChanges();

            //SaveUserRoles(userName, roleId);
            return RedirectToAction("AssignAccountRole");
        }

        //private void SaveUserRoles(string userName, string roleId)
        //{
        //    ApplicationDbContext context = new ApplicationDbContext();
        //    var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

           
        //    try
        //    {
        //        var user = UserManager.FindByName(userName);
        //        var Roles = context.Roles.ToList();
        //        var RoleName = Roles.FirstOrDefault(m => m.Id == roleId).ToString();
        //        UserManager.AddToRole(user.Id, RoleName);
        //        context.SaveChanges();
        //    }
        //    catch (Exception)
        //    {
                
        //        throw;
        //    }

        //}

        [HttpPost]
        public ActionResult DeleteUser(string UserId)
        {
            RemoveUser(UserId);
            return RedirectToAction("AssignAccountRole");
        }

        private void RemoveUser(string userId)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));


            try
            {
                var user = UserManager.FindById(userId);
                UserManager.Delete(user);
                context.SaveChanges();
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

ContentManagementSystem/ContentManagementSystem/ContentManagementSystem.UI/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContentManagementSystem.UI.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ContentManagementSystem.UI.Controllers
{
    public class RolesController : Controller
    {
        public ApplicationDbContext context = new ApplicationDbContext();

        // GET: Roles
        public ActionResult Index()
        {
            var roles = context.Roles.ToList();
            return View(roles);
        }

        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }

        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ContentManagementSystem/ContentManagementSystem/ContentManagementSystem.UI/Views/Role/AssignAccountRole.cshtml
@using ContentManagementSystem.UI.Controllers
@using ContentManagementSystem.UI.Models
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@model ContentManagementSystem.UI.Models.RolesAndUsersViewModel
@{
    ViewBag.Title = "Assign User Roles";
}

<h2>Users with their roles:</h2>

<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>

<div align="center">
    <table class="table table-hover">
        <tr class="danger">
            <th>
                <b>User</b>
            </th>
            <th>
                <b>Select New Role</b>
            </th>
            <th>Current Role</th>
            <th>
                <b>
                    Delete
                </b>
            </th>
        </tr>

        @foreach (ApplicationUser user in Model.AllUsers)
        {
            if (User.Identity.GetUserName() == user.UserName)
            {
                continue;
            }
            else
            {
                <tr class="success">
                    <td>
                        @user.UserName
                    </td>

                    <td>
                        <p>
                         
                            @{
                                var firstOrDefault = Model.AllRoles.FirstOrDefault(r => r.Id == user.Roles.First().RoleId);
                            }


                            @if (firstOrDefault != null)
                            {
                                @firstOrDefault.Name
                            }

                        </p>
                    </td>
                    <td>
                        <form action="SaveUserRole" method="post">
                            @Html.DropDownListFor(m => m.RoleId, Model.RolesDropDown)
                            <input type="hidden" value="@user.Id" name="UserId" />
                            <button type="submit" class="btn btn-primary">Save Role</button>
                        </form>
                    </td>
                    <td>
                        <form action="DeleteUser" method="post">
                            <input type="hidden" value="@user.Id" name="UserId" />
                            <button type="submit" class="btn btn-danger">Delete User</button>
                        </form>
                    </td>
                </tr>
             }
        }
    </table>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContentManagementSystem/ContentManagementSystem/ContentManagementSystem.UI/Views/Role/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>


@using (Html.BeginForm())
{
    <table id="tbrole">
        <tr>
            <td class="success">Enter Role Name To be Created:</td>
            <td class="c">
                @Html.EditorFor(m => m.Name)
            </td>
        </tr>
    </table>
    <input type="submit" value="Create Role" />
}

ContentManagementSystem/ContentManagementSystem/ContentManagementSystem.UI/Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

<h2>Available Roles For Application</h2>

@Html.ActionLink("Create Role", "Create", "Role")

<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>

<table id="tbrole">
    <tr>
        <td class="c">
            Role Name
        </td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="c">
                @item.Name
                @using (Html.BeginForm("Delete", "Role", FormMethod.Post))
                {
                    <input type="hidden" name="Id" value="@item.Id"/>
                    <input type="hidden" name="Name" value="@item.Name"/>
                    <input type ="submit" value ="Delete" class="btn btn-danger"/>
                }
            </td>
        </tr>
    }
</table>