SportsLeague/SportsLeague/SportsLeague.UI/Controllers/GameController.cs
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using Ninject;
using SportsLeague.BLL.Factory;
using SportsLeague.BLL.Managers;
using SportsLeague.Data.Factory;
using SportsLeague.Data.Interfaces;
using SportsLeague.Data.Repositories;
using SportsLeague.Model.Models;
using SportsLeague.UI.Models;

namespace SportsLeague.UI.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameRepository _gameRepo;
        
        public GameController()
        {
            var kernel = new StandardKernel(new ManagerBindings(), new DataBindings());
            kernel.Load(Assembly.GetExecutingAssembly());
            _gameRepo = kernel.Get<IGameRepository>();
        }

        public ActionResult Index()
        {
            var viewModel = new TeamGameVm();
            return View(viewModel);
        }
        
        [HttpPost]
        public ActionResult AddGame(TeamGameVm viewModel)
        {
            if (ModelState.IsValid)
            {
                int gameId = _gameRepo.Create(viewModel.NewGame);
            }
            return RedirectToAction("Index");
        }

        public ActionResult GameResults(int id)
        {
            GamePlayerStatsVM viewModel = new GamePlayerStatsVM(id);
            return View(viewModel);
        }
    }
}

SportsLeague/SportsLeague/SportsLeague.UI/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Ninject;
using Ninject.Modules;
using SportsLeague.BLL.Factory;
using SportsLeague.BLL.Interfaces;
using SportsLeague.BLL.Managers;
using SportsLeague.Data.Factory;
using SportsLeague.Data.Interfaces;
using SportsLeague.Data.Repositories;
using SportsLeague.Model.Models;
using SportsLeague.UI.Models;

namespace SportsLeague.UI.Controllers
{
    public class TeamController : Controller
    {
        private readonly ITeamRepository _teamRepo;
        private readonly IPlayerRepository _playerRepo;
        private readonly ILeagueManager _leagueManager;
        private readonly ITeamManager _teamManager;

        public TeamController()
        {
            var kernel = new StandardKernel(new ManagerBindings(), new DataBindings());
            kernel.Load(Assembly.GetExecutingAssembly());
            _teamRepo = kernel.Get<ITeamRepository>();
            _playerRepo = kernel.Get<IPlayerRepository>();
            _leagueManager = kernel.Get<ILeagueManager>();
            _teamManager = kernel.Get<ITeamManager>();
        }

        public ActionResult CreateTeam()
        {
            return View(_leagueManager.GetLeagues().Data.FirstOrDefault());
        }

        [HttpPost]
        public ActionResult CreateTeamPost(Team team)
        {
            int teamID = _teamRepo.Create(team);
            Team newTeam = _teamManager.GetATeam(teamID).Data;
            var TeamAndPlayer = new TeamPlayersVm()
            {
                NewTeam = newTeam,
                NewPlayer = new Player()
            };
            return View("GetPlayers", TeamAndPlayer);
        }

        [HttpPost]
        public ActionResult GetPlayers(TeamPlayersVm viewModel, int positionID)
        {
            viewModel.NewPlayer.TeamId = viewModel.NewTeam.TeamId;
            viewModel.NewPlayer.Positions.Add(new Position {PositionId = positionID});
            _playerRepo.Create(viewModel.NewPlayer);

            ModelState?.Clear();
            viewModel.NewTeam = _teamManager.GetATeam(viewModel.NewTeam.TeamId).Data;

            viewModel.NewPlayer = new Player();
            
            return View(viewModel);
        }

        public ActionResult TeamHomepage(int id)
        {
            var result = _teamManager.GetATeam(id).Data;
            return View(result);
        }

        [HttpPost]
        public ActionResult DeletePlayer(int playerID, int teamID)
        {
            _playerRepo.Remove(playerID);
            return RedirectToAction("TeamHomepage", new {id = teamID});
        }

        public ActionResult AddPlayer(int teamId)
        {
            Team team = _teamManager.GetATeam(teamId).Data;
            TeamPlayersVm TeamAndPlayer = new TeamPlayersVm()
            {
                NewTeam = team,
                NewPlayer = new Player()
            };
            return View("GetPlayers", TeamAndPlayer);
        }

        public ActionResult TradePlayer()
        {
            return View(_leagueManager.GetLeagues().Data.FirstOrDefault().Teams);
        }

        public ActionResult SelectPlayerTrade(int team1, int team2)
        {
            var vm = new TradePlayerVm();
            vm.Team1 = _teamManager.GetATeam(team1).Data;
            vm.Team2 = _teamManager.GetATeam(team2).Data;

            return View(vm);
        }

        [HttpPost]
        public ActionResult CompletePlayerTrade(int player1, int player2, TradePlayerVm teams)
        {
            var manager = new PlayerManager();
            var firstPlayer = manager.GetPlayer(player1);
            var secondPlayer = manager.GetPlayer(player2);

            firstPlayer.Data.TeamId = teams.Team2.TeamId;
            secondPlayer.Data.TeamId = teams.Team1.TeamId;

            var repo = new PlayerRepo();
            repo.Update(firstPlayer.Data);
            repo.Update(secondPlayer.Data);

            return RedirectToAction("ViewTeams", "League");
        }
     
    }
}

SportsLeague/SportsLeague/SportsLeague.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand" href="#">
                    <img alt="Brand" src="~/Content/Images/logo.png" style="max-height: 55px; max-width: 55px; margin-top: -15px">
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Teams
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("The Teams", "ViewTeams", "League")</li>
                            <li>@Html.ActionLink("Manage Teams", "TradePlayer", "Team")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Create Team", "CreateTeam", "Team")</li>
                        </ul>

                    </li>
                    <li>@Html.ActionLink("Games", "Index", "Game")</li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li class="navbar-right">@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <footer class="footer navbar-fixed-bottom">
            <hr />
            <p style="text-align: center">&copy; @DateTime.Now.Year - League Management</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.9.0/validator.min.js"></script>
    <script src="http://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>