HRPortal/HRPortal.UI/Controllers/TimeSheetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRPortal.BLL;
using HRPortal.UI.Models;
using Models;

namespace HRPortal.UI.Controllers
{
    public class TimeSheetController : Controller
    {
        private readonly EmployeeTimeManager _manager;

        public TimeSheetController()
        {
            _manager = new EmployeeTimeManager();
        }

        public ActionResult SubmitTimesheet()
        {
            var empListAndTimesheet = new EmployeeListAndTimeSheet();
            return View(empListAndTimesheet);
        }

        [HttpPost]
        public ActionResult SubmitTimesheet(EmployeeListAndTimeSheet viewModel)
        {
            if (ModelState.IsValid)
            {
                _manager.AddTimeSheet(viewModel.TimeSheet);
                return RedirectToAction("ViewTimesheet");
            }
            else
            {
                //var empListAndTimesheet = new EmployeeListAndTimeSheet();
                return View(viewModel);
            }
        }

        public ActionResult ViewTimesheet()
        {
            return View(_manager.GetAllEmployees().Data);
        }

        public ActionResult ShowEmployeeInfo(int empId)
        {
            var employeeAndTimesheets = new EmployeeAndListOfTimeSheet(empId);
            return View(employeeAndTimesheets);
        }

        [HttpPost]
        public ActionResult RemoveTimeSheet(int id, int empId)
        {
            Response<TimeSheet> response =  _manager.RemoveTimeSheet(id);
            var employeeAndTimesheets = new EmployeeAndListOfTimeSheet(empId);
            return View("ShowEmployeeInfo", employeeAndTimesheets);
        }
    }
}

HRPortal/HRPortal.UI/Views/TimeSheet/ShowEmployeeInfo.cshtml
@model HRPortal.UI.Models.EmployeeAndListOfTimeSheet

@{
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}

<div class="col-md-8 col-md-offset-2 panel panel-body">
    <div class="panel-body">
        <h2>Employee Summary</h2>
        <div class="form-control">
            <label>Employee Name : </label>
            @Model.Employee.LastName, @Model.Employee.FirstName
        </div>
        <div class="form-control">
            <label>Hire Date : </label>
            @Model.Employee.HireDate.ToString("MMM-dd-yyy")
        </div>
        <div class="form-control">
            <label>Total Hours Worked : </label>
            @Model.TotalHours
        </div>
        <hr/>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td>Name</td>
                    <td>Hours</td>
                    <td>Date</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
            @foreach (var timeSheet in Model.TimesheetList)
            {
                <tr>
                    <td>@Model.Employee.FirstName, @Model.Employee.LastName</td>
                    <td>@timeSheet.Hours</td>
                    <td>@timeSheet.Date.ToString("MMM-dd-yyy")</td>
                    <td>
                        @using (Html.BeginForm("RemoveTimeSheet", "TimeSheet", FormMethod.Post))
                        {
                            <div class="form-group">
                                <input type="hidden" value="@timeSheet.Id" name="id" />
                                <input type="hidden" value="@timeSheet.EmpId" name="empId" />
                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            </div>
                        }
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

HRPortal/HRPortal.UI/Views/TimeSheet/SubmitTimesheet.cshtml
@model HRPortal.UI.Models.EmployeeListAndTimeSheet

@{
    ViewBag.Title = "SubmitTimesheet";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}

<div class="col-md-8 col-md-offset-2">
    <h2 align="center">Submit Timesheet</h2>
    <div class="panel panel-default">
        <div class="panel-body">
            @using (Html.BeginForm("SubmitTimesheet", "TimeSheet", FormMethod.Post))
            {
                @Html.ValidationSummary(true)
                <div align="center">
                    <label for="TimeSheet_EmpId">Employee : </label>
                    @* When Model coming in is different than model going out, you have to use Model.Attribute for the name -- TimeSheet.EmpId *@
                    <select name="TimeSheet.EmpId" id="TimeSheet_EmpId">
                        @foreach (var employee in Model.EmployeeList)
                        {
                            <option value="@employee.Id">@employee.FirstName @employee.LastName</option>
                        }
                    </select>
                    <p>@Html.LabelFor(m => m.TimeSheet.Date): @Html.EditorFor(m => m.TimeSheet.Date)</p>
                    <p>@Html.ValidationMessageFor(m => m.TimeSheet.Hours)</p>
                    <label>Hours Worked : </label>
                    @Html.TextBoxFor(m => m.TimeSheet.Hours)
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            }
        </div>
    </div>
</div>

HRPortal/HRPortal.UI/Views/TimeSheet/ViewTimesheet.cshtml
@model List<Models.Employee>

@{
    ViewBag.Title = "ViewTimesheet";
    Layout = "~/Views/Shared/_HRLayout.cshtml";
}

<div class="col-md-8 col-md-offset-2 panel panel-default">
    <div class="panel-body">
        <h2>View Timesheet</h2>
        @using (Html.BeginForm("ShowEmployeeInfo", "TimeSheet"))
            {
            <div align="center">
                <label>Employee : </label>
                <select name="empId">
                    @foreach (var employee in Model)
                    {
                        <option value="@employee.Id">@employee.FirstName @employee.LastName</option>
                    }
                </select>
                <p>
                    <button type="submit" class="btn btn-default">Submit</button>
                </p>
            </div>
        }
    </div>
</div>